version: "2.4"
services:
  app: 
    build: .
    container_name: app
    restart: unless-stopped
    hostname: app

  nginx:
    image: nginx:alpine
    container_name: nginx
    hostname: nginx
    restart: unless-stopped
    volumes:
    - "/opt/docker_volumes/uwsgi/ssl:/etc/ssl"
    - "/opt/docker_volumes/uwsgi/hello.conf:/etc/nginx/conf.d/default.conf"
    ports:
    - "443:443"
    - "80:80"
