version: "2.4"
services:
  gunicorn:
    build: .
    container_name: gunicorn
    restart: unless-stopped
    hostname: gunicorn
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    env_file:
      - ./.env.app

  db:
    image: postgres:12-alpine
    container_name: db
    hostname: db
    restart: unless-stopped
    healthcheck:
      test: "exit 0"
    volumes:
      - "postgres_data:/var/lib/postgresql/data/"
    env_file:
      - ./.env.db

  web:
    image: nginx:alpine
    container_name: web
    hostname: web
    restart: unless-stopped
    volumes:
    - "/opt/docker_volumes/gunicorn/ssl:/etc/ssl"
    - "/opt/docker_volumes/gunicorn/hello.conf:/etc/nginx/conf.d/default.conf"
    ports:
    - "443:443"
    - "80:80"

volumes:
  postgres_data: