version: "2.4"
services:
  flask:
    build: .
    container_name: flask
    restart: unless-stopped
    hostname: flask
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    env_file:
      - ./.env.app

  db:
    image: postgres:12-alpine
    container_name: db
    hostname: db
    restart: unless-stopped
    healthcheck:
      test: "exit 0"
    volumes:
      - "postgres_data:/var/lib/postgresql/data/"
    env_file:
      - ./.env.db



volumes:
  postgres_data: